### ISSUE TITLE
How to write patterns while maintaining indentation in Python?

### ISSUE THREAD

**Issue by sangwoo-joh** [comby-tools/comby#253]
Hi, thanks for the great tool again!

I want to change the code below:

```python
# Want to change this code
def foo(x):
  f = lambda x: 2**x
  return f(x)

# to this code
def foo(x):
  def f(x): return 2**x
  return f(x)
```

So my pattern for this is:
```toml
[pattern]
match=":[f] = lambda :[x]: :[body]"
rewrite="def :[f](:[x]): return :[body]"
```

Comby succeeded to apply this pattern in some way, but it cannot preserve the indentation like below:

```python
def foo(x):
def  f(x): return 2**x
  return f(x)
```

Is there any way to preserve the indentation depth for the `def` keyword?
Thank you!
