### ISSUE TITLE
How can I preserve the original newline character(whether Newline or Carriage Return) when no rules are applied?

### ISSUE THREAD

**Issue by sangwoo-joh** [comby-tools/comby#319]
For example, for the below code where `^M` as carriage return,

```python
def foo(a: str,^M
            b: str):^M
   ...
```

And I have a rule for rewriting the wrongly typed `string` to `str` as follow:

```toml
match="def :[fun](:[args])"
rewrite="def :[fun](:[args])"
rule='where rewrite :[exp] { ":[var]: string" -> ":[var]: str" }'
```

Since there is no violation in the above code, I didn't expect any modifications to be made. However, after I ran the rule, I found that the original `^M`s were disappeared:

```python
def foo(a: str,
            b: str):
   ...
```

How can I preserve the original newline character?
